
import java.awt.List;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sdw
 */
 
public class PlaceOrder extends javax.swing.JFrame {
   public static ArrayList<String> orderId=new ArrayList<>();
   public static ArrayList<String> adate=new ArrayList<>();
   public static ArrayList<Object> poCustomerId=new ArrayList<>();
    public static ArrayList<Object> poCustomerName=new ArrayList<>();
   public static ArrayList<String> netTotal=new ArrayList<>();
   
static ArrayList<String> itemCode=new ArrayList<>();
  static ArrayList<String> description=new ArrayList<>();
  static ArrayList<String> aqty=new ArrayList<>();
  static ArrayList<String> unitPrice=new ArrayList<>();
 static ArrayList<String> total=new ArrayList<>();
 
 static ArrayList<ArrayList> alitemCode=new ArrayList<>();
 static ArrayList<ArrayList> aldescription=new ArrayList<>();
static ArrayList<ArrayList> alqty=new ArrayList<>();
static ArrayList<ArrayList> alunitPrice=new ArrayList<>();
 ArrayList<ArrayList> altotal=new ArrayList<>();
    
   public static ArrayList<Integer> oqty=new ArrayList<>();
   static int oid=0;
   int qty=0;
   int rt=0;
   Double ntotal=0.0;
    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfOId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbCusId = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lCusName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbItemCode = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lPODes = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        tfQtyOnHand = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfUnitPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfPOQty = new javax.swing.JTextField();
        bSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlaceOrder = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        lnetTotal = new javax.swing.JLabel();
        bPlaceOrder = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        bNerOrder = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Place Order");

        jLabel2.setText("Order Id");

        jLabel3.setText("Date");

        jLabel4.setText("Customer Id");

        cbCusId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCusIdItemStateChanged(evt);
            }
        });

        jLabel5.setText("Name");

        jLabel7.setText("Item Code");

        cbItemCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemCodeItemStateChanged(evt);
            }
        });

        jLabel8.setText("Description");

        lPODes.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Qty on Hand");

        tfQtyOnHand.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel11.setText("Unit Price");

        tfUnitPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel12.setText("Qty");

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");

        tblPlaceOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Description", "Qty", "Unit Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblPlaceOrder);

        jLabel13.setText("Total");

        bPlaceOrder.setText("Place Order");
        bPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlaceOrderActionPerformed(evt);
            }
        });

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        bNerOrder.setText("New Order");
        bNerOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNerOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(lnetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(585, 585, 585)
                        .addComponent(bPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(cbItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbCusId, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfQtyOnHand)
                                    .addComponent(tfPOQty))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(bSave)
                                .addGap(53, 53, 53)
                                .addComponent(jButton2)
                                .addContainerGap(183, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(69, 69, 69)
                                        .addComponent(tfUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(182, 182, 182))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(71, 71, 71)
                                        .addComponent(lCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(64, 64, 64)
                                        .addComponent(lPODes, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfOId))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(80, 80, 80)
                                .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bNerOrder)
                                .addGap(27, 27, 27)
                                .addComponent(bRefresh)
                                .addGap(82, 82, 82))))))
            .addComponent(jSeparator4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRefresh)
                    .addComponent(bNerOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(cbCusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(lCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPODes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfQtyOnHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfPOQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSave)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lnetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bPlaceOrder)
                        .addGap(44, 44, 44))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
//       DefaultComboBoxModel model = (DefaultComboBoxModel) cbCusId.getModel();
//        
//model.addElement(main.id.get(0));

Iterator<String> iter;
iter=main.id.iterator();
cbCusId.removeAllItems();
//cbCusId.addItem("Select Customer Id..");
while(iter.hasNext()){
    
cbCusId.addItem(iter.next());
}

Iterator<String> icter;
icter=Item.icode.iterator();
cbItemCode.removeAllItems();
//cbCusId.addItem("Select Customer Id..");
while(icter.hasNext()){
    
cbItemCode.addItem(icter.next());
}

tfOId.setText("");
        DateFormat datef= new SimpleDateFormat("YYYY/MM/dd");
        Date date=new Date();
        tfDate.setText(datef.format(date));

    }//GEN-LAST:event_bRefreshActionPerformed

    private void cbCusIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCusIdItemStateChanged
        // TODO add your handling code here:
        //if(!cbCusId.getSelectedItem().equals("Select Customer Id.."))
        {int oi=main.id.indexOf(cbCusId.getSelectedItem());
        lCusName.setText(main.name.get(oi));}
        
       
        
    }//GEN-LAST:event_cbCusIdItemStateChanged

    private void cbItemCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemCodeItemStateChanged
 int ii=Item.icode.indexOf(cbItemCode.getSelectedItem());
            System.out.println(ii);
        lPODes.setText(Item.ides.get(ii));
        
        tfQtyOnHand.setText(Integer.toString(Item.iqty.get(ii)));
        tfUnitPrice.setText(Double.toString(Item.iprice.get(ii)));
    }//GEN-LAST:event_cbItemCodeItemStateChanged

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed

        
        int getqty=Integer.parseInt(tfPOQty.getText());
oqty.add(getqty);
      qty++;
      
      Object getItemCode=cbItemCode.getSelectedItem();
      String getDes=lPODes.getText();
      String getUnitPrice=tfUnitPrice.getText();
      Double nntotal=Double.parseDouble(getUnitPrice)*Integer.parseInt(tfPOQty.getText());
      
        
    DefaultTableModel model = (DefaultTableModel) tblPlaceOrder.getModel();
    Object []prow=new Object[]{getItemCode, getDes, tfPOQty.getText(),getUnitPrice,nntotal };
    model.addRow(prow);  
    ntotal+=nntotal;
    lnetTotal.setText(Double.toString(ntotal));
    
      lPODes.setText("");
tfQtyOnHand.setText("");
tfUnitPrice.setText("");
tfPOQty.setText("");  
    }//GEN-LAST:event_bSaveActionPerformed

    private void bNerOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNerOrderActionPerformed
 lPODes.setText("");
tfQtyOnHand.setText("");
tfUnitPrice.setText("");
tfPOQty.setText("");  
tfOId.setText("");
DateFormat datef= new SimpleDateFormat("YYYY/MM/dd");
        Date date=new Date();
        tfDate.setText(datef.format(date));
    }//GEN-LAST:event_bNerOrderActionPerformed

    private void bPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlaceOrderActionPerformed
String getoid=tfOId.getText();
orderId.add(getoid);
  tfOId.setText(""); 
  
  String getdate=tfDate.getText();
adate.add(getdate);
  tfDate.setText(""); 
  
  String getNetTotal=lnetTotal.getText();
netTotal.add(getNetTotal);
  lnetTotal.setText(""); 
  
  String getCusName=lCusName.getText();
poCustomerName.add(getCusName);
  lCusName.setText(""); 
  
  Object getpoCustomerId=cbCusId.getSelectedItem();
poCustomerId.add(getpoCustomerId);

  
        for (int j = 0; j < tblPlaceOrder.getColumnCount(); j++) {         
        
        for (int i = 0; i < tblPlaceOrder.getRowCount(); i++) {           
         switch(j){   
             case 0:  itemCode.add(tblPlaceOrder.getValueAt(i, 0).toString()); break;
             case 1:  description.add(tblPlaceOrder.getValueAt(i, 1).toString()); break;
             case 2:  aqty.add(tblPlaceOrder.getValueAt(i, 2).toString()); break;
             case 3:  unitPrice.add(tblPlaceOrder.getValueAt(i, 3).toString()); break;
             case 4:  total.add(tblPlaceOrder.getValueAt(i, 4).toString()); break;
         }  
        }
          
        }
         
         alitemCode.add(itemCode);
  
   aldescription.add(description);
 
   alqty.add(aqty);
  
   alunitPrice.add(unitPrice);
 
   altotal.add(total);
        
oid++;

DefaultTableModel model=(DefaultTableModel) tblPlaceOrder.getModel();
model.setRowCount(0);
    }//GEN-LAST:event_bPlaceOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bNerOrder;
    private javax.swing.JButton bPlaceOrder;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox<String> cbCusId;
    private javax.swing.JComboBox<String> cbItemCode;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lCusName;
    private javax.swing.JLabel lPODes;
    private javax.swing.JLabel lnetTotal;
    private javax.swing.JTable tblPlaceOrder;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfOId;
    private javax.swing.JTextField tfPOQty;
    private javax.swing.JTextField tfQtyOnHand;
    private javax.swing.JTextField tfUnitPrice;
    // End of variables declaration//GEN-END:variables
}
